### ISSUE TITLE
Generate.Command Issue

### ISSUE THREAD

**Issue by Geoff12889** [dracula/macos-color-picker#2]
I'm receiving the following error when I try to initiate the generate.command script:

> /macos-color-picker/generate.command:4:in `require': cannot load such file -- dracula-yaml-json (LoadError)
> 	from /Users/username/Git/macos-color-picker/generate.command:4:in '\<main\>'

**Comment by Geoff12889** [comment]
Bump. Anyone able to provide a solution? Thanks

**Comment by danielbayley** [comment]
@Geoff12889 I pushed a fix, so please test and report back… Thanks.

**Comment by Geoff12889** [comment]
@danielbayley I'm still experiencing the same issue. I didn't see an update pushed to the generate.command though, was the fix with an external file?

**Comment by danielbayley** [comment]
> I didn't see an update pushed to the generate.command though, was the fix with an external file?

@Geoff12889 Yes, it was a problem elsewhere, with `brew` not having access to the necessary bundled RubyGems, since they aren’t installed by default… Try doing:
~~~ sh
brew update
brew untap dracula/install --force
brew tap dracula/install
brew install --cask dracula-macos-color-picker
~~~
and report back… Thanks.

**Comment by douglasrlee** [comment]
I am also getting this error when trying to install with git clone and the generate command.

Commit: `5073ffcb6867c150c0d15577909da509c6c17208`

![Screen Shot 2022-10-10 at 11 06 46 AM](https://user-images.githubusercontent.com/9452927/194909117-fee4c0b0-96b4-4595-9d8f-317d661cc6d2.png)

**Comment by Geoff12889** [comment]
> > I didn't see an update pushed to the generate.command though, was the fix with an external file?
> 
> @Geoff12889 Yes, it was a problem elsewhere, with `brew` not having access to the necessary bundled RubyGems, since they aren’t installed by default… Try doing:
> 
> ```shell
> brew update
> brew untap dracula/install --force
> brew tap dracula/install
> brew install --cask dracula-macos-color-picker
> ```
> 
> and report back… Thanks.

Received this error:

`Error: No available tap dracula/install.`

**Comment by mayurankv** [comment]
Also have this error
